### ISSUE TITLE
"format_on_save" is not working

### ISSUE THREAD

**Issue by brainplot** [jasjuang/sublime_cmake_format#5]
Hi, the plugin seems to work correctly when I press `CTRL`+`SHIFT`+`C`, however enabling `format_on_save` either in my `.sublime_project` file or in the plugin's global settings doesn't seem to work. I can reproduce the problem both on Windows and Arch Linux, with the latest *stable* version of Sublime Text installed. Here's my `settings` key in my project file:
```JSON
"settings":
{
    "LSP":
    {
        "clangd":
        {
            "enabled": true,
            "command": [
                "clangd",
                "-completion-style=detailed",
                "-pch-storage=memory"
            ]
        }
    },
    "CMakeFormat": {
        "format_on_save": true,
    }
}
```
I tried restarting Sublime multiple times but that doesn't fix the problem. The way I'm testing this is by messing up the indentation and formatting of one of my `CMakeLists.txt` files and trying to hit `CTRL`+`S`, which is exactly how `Clang Format` works, with `hpp`/`cpp` files. However, it does nothing. If I select all and then save, then it works as intended and the `CMakeLists.txt` file gets properly formatted again.

**Comment by jasjuang** [comment]
You might be putting the format on save option on the wrong file. Can you try going to Preferences -> Package Settings -> CMake Format -> Settings - User and then put something like

```
{
    "binary": "cmake-format.exe",
    "format_on_save": true
}
```

and see if it works?

**Comment by brainplot** [comment]
For some reason, doing that made it work. Though I did not put `.exe` because I'm on Linux.
Since `cmake-format` is in my `PATH` I thought that step was not needed, which is also what the `README.md` says. Anyways, thank you for your support!

**Comment by jasjuang** [comment]
That's great!
