### ISSUE TITLE
cmake format OSX, Sublime Text 3 not working 

### ISSUE THREAD

**Issue by KjellKod** [jasjuang/sublime_cmake_format#6]
Hi, 

The formatter works great manually but not when setup to format on save.  

I looked at this issue: https://github.com/jasjuang/sublime_cmake_format/issues/5 and set my user configuration to be similar
```
{
     "binary": "/Library/Frameworks/Python.framework/Versions/3.8/bin/cmake-format",
    "format_on_save": true
}
```

Format on selection manually, or with the short keys work great. `format_on_save` does not work for some reason.

**Comment by jasjuang** [comment]
I only have access to Windows and Linux but I will try my best to help.  Can you confirm that if you type `/Library/Frameworks/Python.framework/Versions/3.8/bin/cmake-format --help` in your terminal, it shows the right output?

**Comment by KjellKod** [comment]
`/Library/Frameworks/Python.framework/Versions/3.8/bin/cmake-format --help` works great.  It outputs the help. 

The selection format works so I'm using that but obviously format-on-save would be sweet

**Comment by jasjuang** [comment]
If you look at the relevant code here https://github.com/jasjuang/sublime_cmake_format/blob/master/cmake_format.py#L310, I don't see any OS specific problem that might cause it to fail.

**Comment by KjellKod** [comment]
the one thing that I've seen that is odd with the package installation is that it does not exist in the prescribed location

Choosing to view the default settings shows a file that cannot be saved since the package directory is not created correctly. 
(obviously editing the default settings shouldn't be done but it COULD be done in case there's an issue with reading the user settings)

When I open the **default** settings for the package I get this (if I would try to save the file)
<img width="543" alt="Screen Shot 2020-07-03 at 2 58 59 PM" src="https://user-images.githubusercontent.com/331742/86497232-0e137680-bd3e-11ea-97c4-623e43a2550f.png">

ls `~/Library/Application\ Support/Sublime\ Text\ 3/Packages/` should show it and it's not there. 
<img width="1108" alt="Screen Shot 2020-07-03 at 3 02 10 PM" src="https://user-images.githubusercontent.com/331742/86497258-30a58f80-bd3e-11ea-9a25-17e34ca6c6eb.png">

**Comment by KjellKod** [comment]
I used the `pip install` and later the `sublime package install` like the repo instructions said

**Comment by KjellKod** [comment]
More clues: 

When I create the missing directory `CMakeFormat` then the file `cmake_format.sublime-settings` is created when I open up the default settings.    It hasn't fixed the issue, however (I also edited the default to have the right path and set "true" for the format on save)

Not sure what else should have happened during the installation but at least the `CMakeFormat` directory was not created as it should have been. Possibly more installation steps also failed?

**Comment by KjellKod** [comment]
Problem solved. I had picked `CMakeEditor` for view syntax. So the manual step worked but not the automatic. 

Changing it to CMake made the automatic work. My bad completely. 
<img width="853" alt="Screen Shot 2020-07-06 at 8 55 01 AM" src="https://user-images.githubusercontent.com/331742/86607842-0256c880-bf67-11ea-91eb-4505e26a2cbe.png">
