### ISSUE TITLE
cmake-format not working, how to debug?

### ISSUE THREAD

**Issue by OlivierLDff** [jasjuang/sublime_cmake_format#7]
Hi, I'm using ST4, and I didn't manage to make this plugin work.
I'm settings the path
![image](https://user-images.githubusercontent.com/17255804/126122449-36c10ac1-5d77-44d9-abda-e70f66c3a542.png)
I can confirm the exec is working from command line.

When I try to format selection, format on save, etc... nothing ever happened.
How can I debug this, is there some logs somewhere?

Thanks, have a nice day.

**Comment by jasjuang** [comment]
I am unsure what you mean by setting the path, but try going to Preferences → Package Settings → CMake Format → Package Settings → Settings - User and put the below in there

```
{
    "format_on_save": true,
    "binary": "C:/Python38/Scripts/cmake-format.exe"
}
```

to see if it works.

**Comment by OlivierLDff** [comment]
Thanks for quick reply.
I was using `CMake Format: Set Path` from command palette, that write into the file `cmake_format.sublime-settings`
File is located in `C:/Users/olivi/AppData/Roaming/Sublime Text 3/Packages/User`.
So I already had the same file as you have.

**Comment by jasjuang** [comment]
If you are sure `C:/Python38/Scripts/cmake-format.exe --help` shows the right output, then I am not sure why it isn't working for you. It worked on my ST4 on Win10. 

One thing you can try is look at the plugin execution output by doing ctrl + ` and try to figure out what is wrong.

**Comment by OlivierLDff** [comment]
Do you have any link in documentation how to open the output? I have french keyboard, and ctrl + ` doesn't seem to do anything

**Comment by jasjuang** [comment]
Try View → Show Console

**Comment by OlivierLDff** [comment]
I was looking for that for ever.

Here is the output:

```
Traceback (most recent call last):
  File "C:\Program Files\Sublime Text\Lib\python33\sublime_plugin.py", line 896, in on_pre_save
    run_view_callbacks('on_pre_save', view_id)
  File "C:\Program Files\Sublime Text\Lib\python33\sublime_plugin.py", line 708, in run_view_callbacks
    callback(v, *args)
  File "C:\Program Files\Sublime Text\Lib\python33\sublime_plugin.py", line 152, in profiler
    return event_handler(*args)
  File "C:\Users\olivi\AppData\Roaming\Sublime Text 3\Installed Packages\CMakeFormat.sublime-package\cmake_format.py", line 314, in on_pre_save
    f.write(body)
  File "./python3.3/encodings/cp1252.py", line 19, in encode
UnicodeEncodeError: 'charmap' codec can't encode characters in position 228-231: character maps to <undefined>
```

So it seems to be an encoding error ? https://stackoverflow.com/questions/27092833/unicodeencodeerror-charmap-codec-cant-encode-characters

**Comment by jasjuang** [comment]
What is the encoding of your file? Is it UTF-8? Are you able to run `cmake-format` on this particular file via command line successfully?

**Comment by OlivierLDff** [comment]
From `file CMakeLists.txt` I get `CMakeLists.txt: Unicode text, UTF-8 text, with CRLF line terminators`
I can run `cmake-format -i CMakeLists.txt` with success.
I also tried the VScode extension that also work.

**Comment by OlivierLDff** [comment]
So I found what what is the problem

I'm using the character `─` in my comments, this cause the crash.

**Comment by OlivierLDff** [comment]
So applying https://stackoverflow.com/a/42495690/12334315 it works for my file.
Line 313: `with open(view.file_name(), "w", encoding="utf-8") as f:`

But it doesn't look "universal" code to me and look like ugly hack if people use other encoding scheme.
Real question here, are people using something else than utf-8?

Interesting from comments on stackoverflow:
> In mac(python 3) works perfectly with just open without encoding, but in windows(w10, python3) is not an option. Just works in that way, with encoding="utf-8" param.

Is also tried to modify environment variable but that didn't work:
```python
os.environ["PYTHONIOENCODING"] = "utf-8"
os.environ["PYTHONLEGACYWINDOWSSTDIO"] = "utf-8"
os.environ["PYTHONLEGACYWINDOWSIOENCODING"] = "utf-8"
```

**Comment by OlivierLDff** [comment]
Ok so I found multiple way to fix it in a clean way:

## Solution 1

Determine actual encoding of file:
```python
# code from https://stackoverflow.com/a/14734061/12334315
def determine_file_encoding(file_name):
    encodings = ['utf-8', 'windows-1250', 'windows-1252', 'latin1', 'iso-8859-1']
    for e in encodings:
        try:
            fh = codecs.open(file_name, 'r', encoding=e)
            fh.readlines()
            fh.seek(0)
        except UnicodeDecodeError:
            continue
        else:
            return e
    return 'utf-8'
```

Then use this function to open the file: 

```python
with open(view.file_name(), "w", encoding=determine_file_encoding(view.file_name())) as f:
```

## Solution 2:

Use the `input_encoding` from settings:

```python
with open(view.file_name(), "w", encoding=input_encoding) as f:
```

I can make a PR if you want. Tell me which solution you prefer.

**Comment by jasjuang** [comment]
Using the `input_encoding` from settings seems to make more sense. Have you tested whether solution 2 fixes your problem?

**Comment by OlivierLDff** [comment]
Yes 2 solutions work like a charm

**Comment by jasjuang** [comment]
PR with solution 2 will be very welcomed.
