### ISSUE TITLE
Add info in readme: how to use style from file

### ISSUE THREAD

**Issue by OlivierLDff** [jasjuang/sublime_cmake_format#8]
From reading the code I figured out how to use style from a `.cmake-format` file.
I set `"style": "File",` in the settings files and it works.
If I set any other string than `custom` is should work using a config file.

Maybe it would be nice to have a command to select the style like the clang-format sublime text plugin?
https://github.com/rosshemsley/SublimeClangFormat/blob/2e92c03d9c25ede096654f1bee8ca119e2e67397/clang_format.sublime-commands#L2

And also a word in Readme about that? In the https://github.com/jasjuang/sublime_cmake_format#use paragraph

**Comment by jasjuang** [comment]
I don't use command palette as frequent, so adding a command to select the style didn't cross my mind. With that being said, any PR for improvements from all aspects are very welcome.
